dataset: cifar100
net_type: wresnet28_10
depth: 28
alpha: 10

epochs: 300
batch_size: 128
lr: 0.025
momentum: 0.9
lr_schedule:
  type: 'cosine'

gradient_clip: 5
weight_decay: 0.0002

cutout: 16

cutmix:
  beta: 1.0
  prob: 0.5
  num: 1
