dataset: cifar100
net_type: pyramidnet
depth: 200
alpha: 240

epochs: 300
batch_size: 64
lr: 0.25
momentum: 0.9
lr_schedule:
  type: 'pyramid'

gradient_clip: 0
weight_decay: 0.0001

cutout: 0

cutmix:
  beta: 1.0
  prob: 0.5
  num: 1
