dataset: cifar100
net_type: pyramidnet
depth: 272
alpha: 200

epochs: 1800
batch_size: 64
lr: 0.05
momentum: 0.9
lr_schedule:
  type: 'pyramid'

gradient_clip: 5
weight_decay: 0.00005

cutmix:
  beta: 1.0
  prob: 0.5
  num: 1
